// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Tr3anMZHpDvY-OZrCo_F85NH1H0vEOw',
    appId: '1:21459467072:web:80185d46cdb071394e18a5',
    messagingSenderId: '21459467072',
    projectId: 'field-force-management-52800',
    authDomain: 'field-force-management-52800.firebaseapp.com',
    storageBucket: 'field-force-management-52800.appspot.com',
    measurementId: 'G-PQ38BSNHQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASzl22tPY7GNY2__cRsCZ9we3UkpNmmqA',
    appId: '1:21459467072:android:2febe43e8d60af534e18a5',
    messagingSenderId: '21459467072',
    projectId: 'field-force-management-52800',
    storageBucket: 'field-force-management-52800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWRKNJpDobqraaMzkNIgq-vuEZgQ5lhf0',
    appId: '1:21459467072:ios:5f1dd2fab40d55124e18a5',
    messagingSenderId: '21459467072',
    projectId: 'field-force-management-52800',
    storageBucket: 'field-force-management-52800.appspot.com',
    iosBundleId: 'com.example.fieldForceManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWRKNJpDobqraaMzkNIgq-vuEZgQ5lhf0',
    appId: '1:21459467072:ios:5f1dd2fab40d55124e18a5',
    messagingSenderId: '21459467072',
    projectId: 'field-force-management-52800',
    storageBucket: 'field-force-management-52800.appspot.com',
    iosBundleId: 'com.example.fieldForceManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Tr3anMZHpDvY-OZrCo_F85NH1H0vEOw',
    appId: '1:21459467072:web:4fdd737ae6e4211a4e18a5',
    messagingSenderId: '21459467072',
    projectId: 'field-force-management-52800',
    authDomain: 'field-force-management-52800.firebaseapp.com',
    storageBucket: 'field-force-management-52800.appspot.com',
    measurementId: 'G-JSW9V0CGDH',
  );

}